#!/usr/bin/env bash
if [ -z "$1" ]
  then
    docker-compose exec --user www-data web_server grunt exec
    docker-compose exec --user www-data web_server grunt less
    docker-compose exec --user www-data web_server grunt deploy
    docker-compose exec --user www-data web_server grunt watch
else
    docker-compose exec --user www-data web_server grunt exec:$@
    docker-compose exec --user www-data web_server grunt less:$@
    docker-compose exec --user www-data web_server grunt watch:$@
fi
